#!/usr/bin/env bash
# setup.sh — idempotent installer for claude-anima.
#
# Prompts for: Telegram bot token, chat id, project dir, memory dir, waking hours.
# Then: writes the plugin .env (gitignored), seeds starter memory/HEARTBEAT files,
# and installs a per-hour launchd agent (macOS) from the template.
#
# Safe to re-run: existing answers are shown as defaults; existing files are never
# clobbered without asking. NEVER writes secrets into the repo — only into the
# gitignored .env and your private config.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

say()  { printf '\033[1m%s\033[0m\n' "$*"; }
note() { printf '  %s\n' "$*"; }

# ask VAR "Prompt" "default"  — reads into VAR, falling back to default on empty.
ask() {
  local __var="$1" __prompt="$2" __default="${3:-}" __reply
  if [ -n "$__default" ]; then
    printf '%s [%s]: ' "$__prompt" "$__default" >&2
  else
    printf '%s: ' "$__prompt" >&2
  fi
  read -r __reply || true
  [ -n "$__reply" ] || __reply="$__default"
  printf -v "$__var" '%s' "$__reply"
}

# Load existing answers so re-runs default to what's already configured.
[ -f "$ENV_FILE" ] && { set -a; . "$ENV_FILE"; set +a; }

say "claude-anima setup"
note "Config + secrets go in $ENV_FILE (gitignored — never committed)."
echo

# --- 1. Telegram credentials ---------------------------------------------------
say "1) Telegram bot (for notifications)"
note "Create a bot with @BotFather, then DM it once so it can message you."
ask TELEGRAM_BOT_TOKEN "Bot token" "${TELEGRAM_BOT_TOKEN:-}"
ask TELEGRAM_CHAT_ID   "Your chat id" "${TELEGRAM_CHAT_ID:-}"
echo

# --- 2. Project + memory dirs --------------------------------------------------
say "2) Workspace"
ask CLAUDE_ANIMA_PROJECT_DIR "Project dir the heartbeat runs in" \
    "${CLAUDE_ANIMA_PROJECT_DIR:-$HOME}"
ask MEMORY_DIR "Memory dir (IDENTITY/USER/SOUL/MEMORY + HEARTBEAT live here)" \
    "${MEMORY_DIR:-$CLAUDE_ANIMA_PROJECT_DIR}"
echo

# --- 3. Waking hours -----------------------------------------------------------
say "3) Waking hours (hourly, on the hour)"
ask WAKE_START "First hour to wake (0-23)" "${WAKE_START:-9}"
ask WAKE_END   "Last hour to wake (0-23)"  "${WAKE_END:-22}"
echo

# --- Write .env ----------------------------------------------------------------
umask 077
cat > "$ENV_FILE" <<EOF
# claude-anima config — generated by setup.sh. Gitignored. Do NOT commit.
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
CLAUDE_ANIMA_PROJECT_DIR=$CLAUDE_ANIMA_PROJECT_DIR
MEMORY_DIR=$MEMORY_DIR
EOF
note "Wrote $ENV_FILE (chmod 600)."

# --- Seed memory + HEARTBEAT files (never overwrite) ---------------------------
say "4) Seeding starter files in $MEMORY_DIR"
mkdir -p "$MEMORY_DIR"
for f in IDENTITY.md USER.md SOUL.md HEARTBEAT.md; do
  if [ -f "$MEMORY_DIR/$f" ]; then
    note "kept existing $f"
  elif [ -f "$ROOT/templates/$f" ]; then
    cp "$ROOT/templates/$f" "$MEMORY_DIR/$f"
    note "created $f from template"
  fi
done
[ -f "$MEMORY_DIR/MEMORY.md" ] || { printf '# MEMORY\n\n> Distilled durable memory. One line per fact.\n' > "$MEMORY_DIR/MEMORY.md"; note "created MEMORY.md"; }
echo

# --- Install launchd agent (macOS) ---------------------------------------------
say "5) Scheduler"
if [ "$(uname)" != "Darwin" ]; then
  note "Not macOS — skipping launchd. Wire $ROOT/scripts/heartbeat.sh into cron:"
  note "  0 ${WAKE_START}-${WAKE_END} * * *  $ROOT/scripts/heartbeat.sh"
else
  LABEL="com.claude-anima.$(id -un)"
  PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
  intervals=""
  h=$WAKE_START
  while [ "$h" -le "$WAKE_END" ]; do
    intervals="$intervals    <dict><key>Hour</key><integer>$h</integer><key>Minute</key><integer>0</integer></dict>
"
    h=$((h+1))
  done
  mkdir -p "$HOME/Library/LaunchAgents"
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/zsh</string>
    <string>-lc</string>
    <string>$ROOT/scripts/heartbeat.sh</string>
  </array>
  <key>StartCalendarInterval</key>
  <array>
$intervals  </array>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
EOF
  launchctl unload "$PLIST" 2>/dev/null || true
  launchctl load "$PLIST"
  note "Installed + loaded $PLIST (label $LABEL)."
  note "Wakes hourly ${WAKE_START}:00–${WAKE_END}:00."
fi
echo

# --- Verify --------------------------------------------------------------------
say "6) Verify"
if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
  if "$ROOT/scripts/tg_notify.sh" "claude-anima: setup complete ✅" 2>/dev/null; then
    note "Sent you a test Telegram message — check your phone."
  else
    note "Test notify failed — re-check token/chat id in $ENV_FILE."
  fi
else
  note "No Telegram creds given — notifications disabled until you set them."
fi
echo
say "Done. Edit $MEMORY_DIR/HEARTBEAT.md to tell your agent what to check."
